version: 0.2

phases:
  pre_build:
    commands:
     - aws s3 rm s3://simple-website-432434234123/ --recursive
  build:
    commands:
     - aws s3 cp . s3://simple-website-432434234123/ --recursive
